version: "3"
services:
  vendor-portal:
    image: rupakrpk93/selenium
    environment:
    - BROWSER
    - HUB_HOST=hub
    - TEST_SUITE=vendor-portal.xml
    - THREAD_COUNT=3
    volumes:
    - ./output/vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
    image: rupakrpk93/selenium
    environment:
    - BROWSER
    - HUB_HOST=hub
    - TEST_SUITE=flight-reservation.xml
    - THREAD_COUNT=4
    volumes:
    - ./output/flight-reservation:/home/selenium-docker/test-output