version: "3"
services:
  vendor-portal:
    image: rupakrpk93/selenium
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - TEST_SUITE=vendor-portal.xml
    - THREAD_COUNT=3
    volumes:
    - C:\my-project\project\learning\docker\workspace\06-jenkins-ci-cd\08-runner-approach-1\output\vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
    image: rupakrpk93/selenium
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub
    - TEST_SUITE=flight-reservation.xml
    - THREAD_COUNT=4
    volumes:
    - C:\my-project\project\learning\docker\workspace\06-jenkins-ci-cd\08-runner-approach-1\output\flight-reservation:/home/selenium-docker/test-output